"""SQLAlchemy 2.0 declarative models for the credit-risk-ml-pipeline.

These four tables form the schema contract for all downstream phases.
Schema decisions here cascade to every phase — do not alter column names
or types without a corresponding Alembic migration.
"""

from typing import Optional

from sqlalchemy import (
    Boolean,
    CheckConstraint,
    Float,
    ForeignKey,
    Integer,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.dialects.postgresql import JSON, UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column
from sqlalchemy.sql import func, text


class Base(DeclarativeBase):
    """Shared declarative base for all ORM models."""

    pass


class Prediction(Base):
    """Stores every prediction emitted by the scoring API.

    The ``path`` column distinguishes between model-assigned predictions
    (path='model') and checkerboard-pattern counterfactual predictions
    (path='checkerboard'). This distinction is required by the CB-PDD
    router introduced in Phase 3; it must exist from day one because
    retroactively adding it after rows are inserted breaks the algorithm.

    Attributes:
        id: UUID primary key generated by PostgreSQL gen_random_uuid().
        predicted_at: Timestamp when the prediction was produced.
        model_version: MLflow model alias or version string (e.g. "@champion").
        features: Raw JSON feature dict submitted with the scoring request.
        score: Predicted probability of default, in [0, 1].
        decision: Lending decision derived from score threshold.
        path: Routing label — 'model' or 'checkerboard'.
        simulation_day: Integer day index for simulator-generated rows;
            NULL for live predictions.
    """

    __tablename__ = "predictions"
    __table_args__ = (
        CheckConstraint("decision IN ('approved', 'denied')", name="ck_predictions_decision"),
        CheckConstraint("path IN ('model', 'checkerboard')", name="ck_predictions_path"),
    )

    id: Mapped[str] = mapped_column(
        UUID(as_uuid=False),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )
    predicted_at: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        server_default=func.now(),
    )
    model_version: Mapped[str] = mapped_column(String(50), nullable=False)
    features: Mapped[dict] = mapped_column(JSON, nullable=False)
    score: Mapped[float] = mapped_column(Float, nullable=False)
    decision: Mapped[str] = mapped_column(String(10), nullable=False)
    path: Mapped[str] = mapped_column(String(20), nullable=False)
    simulation_day: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)


class Outcome(Base):
    """Records the observed real-world outcome for a prediction.

    Each prediction may have at most one outcome row (unique constraint
    on ``prediction_id``). The two timestamp columns serve different
    analytical purposes:

    - ``predicted_at`` is copied from the linked prediction row and
      represents *when the model saw the applicant*.
    - ``outcome_received_at`` is *when we learned the actual default
      status* — this is the label delay, and Phase 4 (SIM-04) reads it
      to simulate realistic feedback lag.

    Attributes:
        id: UUID primary key.
        prediction_id: Foreign key to predictions.id (unique — one
            outcome per prediction).
        actual_default: True if the applicant actually defaulted.
        predicted_at: Copied from predictions.predicted_at at write time.
        outcome_received_at: Timestamp when the outcome was received —
            separate from predicted_at to capture label delay.
    """

    __tablename__ = "outcomes"

    id: Mapped[str] = mapped_column(
        UUID(as_uuid=False),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )
    prediction_id: Mapped[str] = mapped_column(
        UUID(as_uuid=False),
        ForeignKey("predictions.id"),
        nullable=False,
        unique=True,
    )
    actual_default: Mapped[bool] = mapped_column(Boolean, nullable=False)
    predicted_at: Mapped[str] = mapped_column(Text, nullable=False)
    outcome_received_at: Mapped[str] = mapped_column(Text, nullable=False)


class DriftScore(Base):
    """Stores the CB-PDD drift score computed by the Airflow drift task.

    Each row represents one drift computation window. Phase 4 reads
    ``psi_score`` for PSI-based baseline comparison; this column is
    nullable because PSI is only available once a reference distribution
    is established (after warm-up period).

    Attributes:
        id: UUID primary key.
        computed_at: When this score was computed.
        drift_score: The CB-PDD performative drift score.
        psi_score: Population Stability Index score (nullable until
            baseline is established in Phase 4 DRIFT-05).
        threshold_crossed: True when drift_score exceeded the threshold.
        window_days: Number of days in the rolling window for this score.
        trial_count: Number of prediction trials used in computation;
            nullable for scores computed before trial tracking was added.
    """

    __tablename__ = "drift_scores"

    id: Mapped[str] = mapped_column(
        UUID(as_uuid=False),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )
    computed_at: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        server_default=func.now(),
    )
    drift_score: Mapped[float] = mapped_column(Float, nullable=False)
    psi_score: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    threshold_crossed: Mapped[bool] = mapped_column(Boolean, nullable=False)
    window_days: Mapped[int] = mapped_column(Integer, nullable=False)
    trial_count: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)


class Alert(Base):
    """Records a drift alert and the retraining outcome.

    Fired when a DriftScore crosses the configured threshold. The
    ``retrain_run_id`` and ``promoted`` columns are nullable because
    retraining may be skipped (e.g. cooldown period, manual override).

    Attributes:
        id: UUID primary key.
        fired_at: When the alert was triggered.
        drift_score: The drift score value that triggered this alert.
        retrain_run_id: MLflow run ID of the retraining job; NULL when
            retraining was skipped or not yet started.
        promoted: True if the new model was promoted to champion; NULL
            when retraining was skipped.
    """

    __tablename__ = "alerts"

    id: Mapped[str] = mapped_column(
        UUID(as_uuid=False),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )
    fired_at: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        server_default=func.now(),
    )
    drift_score: Mapped[float] = mapped_column(Float, nullable=False)
    retrain_run_id: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    promoted: Mapped[Optional[bool]] = mapped_column(Boolean, nullable=True)
